FROM node:8.10

ENV MONGODB_URI='mongodb://localhost:27017/realestate'

WORKDIR /usr/src/app

COPY . /usr/src/app/

RUN npm install

EXPOSE 5000

HEALTHCHECK --interval=2m --timeout=5s --start-period=2m \
    CMD nc -z -w5 127.0.0.1 5080 || exit 1

CMD echo "Warming up" && sleep 5 && npm start
















